###############################################################################
## BETA (SPLASH) SCREEN 
#############################################################################
<BetaScreen>:
    name: "betascreen"
    MDFloatLayout:
        Image:
            source: 'app_design/assets/no.gif'
            allow_stretch: True
            anim_delay: 0
            anim_reset: True
            size_hint: 1, 1
