<FutureResultScreen>:
    MDBoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: "Smart Stocks by Jacob E Bickus"
            left_action_items: [["menu", lambda x: app.menu_bar.open_menu(x)]]
            right_action_items: [["account-circle", lambda x: app.menu_bar.callback_right()]]
            elevation: 5
            pos_hint: {"top": 1}

        MDScrollView:
            MDGridLayout:
                id: main_layout 
                cols: 1
                padding: dp(10)
                spacing: dp(20)
                size_hint_y: None
                height: self.minimum_height
                pos_hint: {"center_x": 0.5}
                
                MDLabel:
                    text: "Price Prediction Tool Results"
                    font_size: "36sp"
                    adaptive_size: True
                    color: "grey"
                    pos_hint: {"center_x": 0.5}