<LuckyScreen>:
    
    MDBoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: "Smart Stocks by Jacob E Bickus"
            left_action_items: [["menu", lambda x: app.menu_bar.open_menu(x)]]
            right_action_items: [["account-circle", lambda x: app.menu_bar.callback_right()]]
            elevation: 5
            pos_hint: {"top": 1}

        MDScrollView:
            MDGridLayout:
                id: main_layout 
                cols: 1
                padding: dp(10)
                spacing: dp(20)
                size_hint_y: None
                height: self.minimum_height
                pos_hint: {"center_x": 0.5}
                
                MDLabel:
                    text: "Feeling Lucky"
                    font_size: "36sp"
                    adaptive_size: True
                    color: "grey"
                    pos_hint: {"center_x": 0.5}

                Widget:
                    size_hint_y: None
                    height: dp(20)

                MDGridLayout:
                    cols: 3
                    size_hint_y: None 
                    height: dp(80)
                    pos_hint: {"center_x":0.5}
                    spacing: dp(16)

                    MDLabel:
                        text: "Number to Research"
                        pos_hint: {"center_x": 0.4, "center_y": 0.5}

                    MDSlider:
                        id: slider 
                        min: 1
                        max: 200
                        step: 1
                        orientation: 'horizontal'
                        size_hint_x: 0.85
                        pos_hint: {"center_x": 0.75}
                        height: dp(40)
                        thumb_size: dp(24)

                    MDLabel:
                        text: str(slider.value)

                MDGridLayout:
                    cols: 3 
                    size_hint_y: None 
                    height: dp(80)
                    pos_hint: {"center_x":0.5}
                    spacing: dp(16)      

                    MDLabel:
                        text: "Number to Highlight"
                        pos_hint: {"center_x": 0.4, "center_y": 0.5}

                    MDSlider:
                        id: slider2 
                        min: 1
                        max: 10
                        step: 1
                        orientation: 'horizontal'
                        size_hint_x: 0.85
                        pos_hint: {"center_x": 0.75}
                        height: dp(40)
                        thumb_size: dp(24)

                    MDLabel:
                        text: str(slider2.value)
                
                MDTextField:
                    id: min_price_id
                    mode: "rectangle"
                    hint_text: 'Minimum Price'
                    helper_text: "Minimum Price of Research Stocks"
                    pos_hint: {"center_x": .5, 'center_y': .5}
                    size_hint_x: .35
                    theme_text_color: "Custom"
                    text_color_normal: "black"
                    text_color_focus: "black"
                    line_color_normal: "orange"
                    line_color_focus: "white"
                    fill_color_normal: "grey"
                    fill_color_focus: "white"

                MDTextField:
                    id: max_price_id
                    mode: "rectangle"
                    hint_text: 'Maximum Price'
                    helper_text: "Maximum Price of Research Stocks"
                    pos_hint: {"center_x": .5, 'center_y': .5}
                    size_hint_x: .35
                    theme_text_color: "Custom"
                    text_color_normal: "black"
                    text_color_focus: "black"
                    line_color_normal: "orange"
                    line_color_focus: "white"
                    fill_color_normal: "grey"
                    fill_color_focus: "white"

                
                MDGridLayout:
                    cols: 2
                    size_hint_y: None
                    height: self.minimum_height
                    pos_hint: {"center_x": 0.5}
                    padding: "24dp"
                    spacing: "48dp"

                    MDLabel:
                        text: "Plot SAM"
                        size_hint_x: None
                        width: "120dp"
                        pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDSwitch:
                        id: plot_sam_id
                        active: False
                        icon_active: "check"
                        icon_inactive: "close"
                        icon_active_color: "white"
                        icon_inactive_color: "grey"
                        pos_hint: {"center_y": 0.5}

                Widget:
                    size_hint_y: None
                    height: dp(20)