###############################################################################
## MAIN (SPLASH) SCREEN 
#############################################################################
MDScreen:
    name: "mainscreen"
    on_enter: self.ids.progress.start()

    MDFloatLayout:
        Image:
            source: 'app_design/kah.gif'  # Make sure the path to your gif is correct
            allow_stretch: True 
            anim_delay: 0
            anim_reset: True 
            size_hint: 1, 1  # Ensure the image covers the entire screen

        MDBoxLayout:
            pos_hint: {'center_y': 0.3, 'center_x': 0.5}
            padding: '10dp'
            size_hint_x: 0.7

            MDProgressBar:
                id: progress 
                orientation: 'horizontal'
                type: 'indeterminate'
                running_duration: 1
                catching_duration: 1
                size_hint_y: 0.05
                size_hint_x: 0.5