<MyCard>:
    padding: "8dp"
    size_hint: None, None
    size: "480dp", "200dp"
    on_press: root.on_press()

    MDRelativeLayout:
        MDIconButton:
            icon: "dots-vertical"
            pos_hint: {"top": 1, "right": 1}

        MDLabel:
            text: root.text
            adaptive_size: True
            color: "grey"
            pos: "12dp", "12dp"
            bold: True

<MenuScreen>:
    BoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: "Smart Stocks by Jacob E Bickus"
            left_action_items: [["menu", lambda x: app.menu_bar.open_menu(x)]]
            right_action_items: [["account-circle", lambda x: app.menu_bar.callback_right()]]
            elevation: 10
            height: dp(96)

        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None  # To make sure the top bar doesn't get squished
            height: dp(72)  # Standard height for toolbars

        Widget:
            size_hint_y: 0.1

        MDGridLayout:
            id: box
            cols: 2
            adaptive_size: True
            spacing: "12dp"
            pos_hint: {'center_x': 0.5}
            md_bg_color: app.theme_cls.primary_color

        Widget:
            size_hint_y: 0.1
