<LoginPage>:
    MDFloatLayout:
        md_bg_color: 1, 1, 1, 1
        Image:
            source: "logo.png"
            pos_hint: {"center_x": .50, "top":1}
            size_hint: None, None   # Adjust size_hint as needed (width, height)
            size_hint: 0.25, 0.25
        MDLabel:
            text: "Smart Stocks Log In"
            pos_hint: {"center_x": 0.5, "center_y":.65}
            size_hint: 0.5, 0.10
            halign: "center"
            font_name: "fonts/Poppins-SemiBold.ttf"
            font_size: "40sp"
            theme_text_color: "Custom"
            text_color: 60/255, 43/255, 117/255, 1
        MDFloatLayout:
            size_hint: .85, 0.08
            pos_hint: {"center_x": 0.5, "center_y":0.58}
            canvas:
                Color:
                    rgb: (238/255, 238/255, 238/255, 1)
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [25]
            TextInput:
                hint_text: "Email"
                size_hint: 1, None
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                height: self.minimum_height
                multiline: False
                cursor_color: 96/255, 74/255, 215/255, 1
                cursor_width: "2sp"
                foreground_color: 96/255, 74/255, 215/255, 1
                background_color: 0,0,0,0
                padding: 15
                font_name: "fonts/Poppins-Regular.ttf"
                font_size: "18sp"
        MDFloatLayout:
            size_hint: .85, 0.08
            pos_hint: {"center_x": 0.5, "center_y":0.48}  # Adjusted pos_hint to avoid overlap with the first TextInput
            canvas:
                Color:
                    rgb: (238/255, 238/255, 238/255, 1)
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [25]
            TextInput:
                hint_text: "Password"
                password: True
                size_hint: 1, 1
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                height: self.minimum_height
                multiline: False
                cursor_color: 96/255, 74/255, 215/255, 1
                cursor_width: "2sp"
                foreground_color: 96/255, 74/255, 215/255, 1
                background_color: 0,0,0,0
                padding: 15
                font_name: "fonts/Poppins-Regular.ttf"
                font_size: "18sp"
        MDFloatLayout:
            size_hint: 0.5, 0.10
            pos_hint:{"center_x":0.5, "center_y":0.38}
            Button:
                text: "Forget your password?"
                font_name: "fonts/Poppins-Regular.ttf"
                background_color: 1,1,1,0 # transparent
                color: 246/255, 135/255, 177/255, 1
                pos_hint: {"center_x":0.5, "top":1}
                size_hint: 1, .5
                font_size: "20sp"
                on_press: root.forgot_password(self)
            Button:
                text: "Create an Account"
                font_name: "fonts/Poppins-Regular.ttf"
                background_color: 1,1,1,0 # transparent
                color: 246/255, 135/255, 177/255, 1
                pos_hint: {"center_x":0.5, "top":0.5}
                size_hint: 1, .5
                font_size: "20sp"
                on_press: root.create_account(self)
        MDFloatLayout:
            size_hint: .5, 0.05
            pos_hint: {"center_x":0.5, "center_y":0.25}
            canvas:
                Color:
                    rgb: (238/255, 238/255, 238/255, 1)
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [25]
            Button:
                text: "LOGIN"
                font_name: "fonts/Poppins-SemiBold.ttf"
                font_size: "36sp"
                size_hint: 1, 1
                pos_hint: {"center_x": .5, "center_y":.5}
                background_color: 0,0,0,0
                canvas.before:
                    Color:
                        rgb: 50/255,200/255,50/255,1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [23]
                on_press: root.login(self)
