from kivy.lang import Builder
import logging

# Ensure logging.basicConfig is not called after setting the level for your logger
logger = logging.getLogger(__name__)

class SmartStocksBuilder:
    def __init__(self):
        Builder.load_file('app_design/kv_files/login.kv') 
        logger.info("login.kv loaded.")
        Builder.load_file('app_design/kv_files/menu.kv')
        logger.info("menu.kv loaded.")
        Builder.load_file('app_design/kv_files/createreportscreen.kv')
        logger.info("createreportscreen.kv loaded.")
        Builder.load_file('app_design/kv_files/future.kv')
        logger.info('future.kv loaded.')
        Builder.load_file('app_design/kv_files/futureresultscreen.kv')
        logger.info("futureresultscreen kv loaded.")
        Builder.load_file('app_design/kv_files/luckyscreen.kv')
        logger.info("luckyscreen kv loaded.")
        Builder.load_file("app_design/kv_files/luckyresultscreen.kv")
        logger.info("luckyresultscreen loaded.")
        Builder.load_file("app_design/kv_files/daytraderscreen.kv")
        logger.info("daytraderscreen.kv loaded.")
        Builder.load_file("app_design/kv_files/schedulereportscreen.kv")
        logger.info("schedulereportscreen loaded.")
        Builder.load_file("app_design/kv_files/betascreen.kv")
        logger.info("betascreen.kv loaded")
        Builder.load_file("app_design/kv_files/topstockscreen.kv")
        logger.info("topstockscreen loaded.")
        Builder.load_file("app_design/kv_files/aboutscreen.kv")
        logger.info("aboutscreen.kv loaded.")
        Builder.load_file("app_design/kv_files/feedbackscreen.kv")
        logger.info("feedbackscreen.kv loaded.")
        Builder.load_file("app_design/kv_files/profilescreen.kv")
        logger.info("profilescreen.kv loaded.")
        Builder.load_file("app_design/kv_files/comparestockscreen.kv")
        logger.info("comparestockscreen.kv loaded.")
        Builder.load_file("app_design/kv_files/comparestocksoutputscreen.kv")
        logger.info("comparestocksoutputscreen.kv loaded.")